# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/killian/Bureau/Atise/Sandbox/design-Zynq/design_mars/src/MarsZX3_EB1.xdc

# Block Designs: bd/MarsZX3/MarsZX3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3 || ORIG_REF_NAME==MarsZX3} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_processing_system7_0_0/MarsZX3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_processing_system7_0_0 || ORIG_REF_NAME==MarsZX3_processing_system7_0_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_xlconstant_0_1/MarsZX3_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_xlconstant_0_1 || ORIG_REF_NAME==MarsZX3_xlconstant_0_1} -quiet] -quiet

# XDC: bd/MarsZX3/MarsZX3_ooc.xdc
